FROM ubuntu:18.04

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-add-repository ppa:elmer-csc-ubuntu/elmer-csc-ppa && apt-get update && apt-get install -y elmerfem-csc rsh-client